apiVersion: v1
kind: Service
metadata:
  name: wp_lb_ingress # the name of our service
spec:
  type: loadBalancer
  selector:
    app: wp # pods are deployed with the label app=wp
  ports:
    - port: 80